version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

formats:
  - pdf

python:
  version: 3
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt